version: '2'

services:
  bet-wa:
    container_name: bet-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '5000:5000'
    
